@host = http://localhost:5295

POST {{host}}/hello
Accept: text/plain
Content-Type: application/json

"Hello There!"

###

POST {{host}}/chat/
Accept: text/plain
Content-Type: application/json

"Hello World, let's chat!"

###

